preview:
  title: 'Shulker Box Preview:' # GUI name for the preview inventory (Color codes supported)
  is-backpack: false # 'true' = Can interact with contents | 'false' = Preview/Can't interact
  toggle-command: true # 'true' = Need to use /sbp-use <true/false> | 'false' removes the need for this
enabled-worlds:
  - 'world'
  - 'world_nether'
  - 'world_the_end'
language:
  toggle-feedback-error: '&7[&c&l!&7] &4Invalid arguments used! Please use "true" or "false".'
  toggle-feedback-successful: '&7[&a&l!&7] &aUpdated preferences.'
  reload-successful: '&7[&a&l!&7] &aReloaded Successfully!'
